services:
  - type: worker
    name: botcrypto-worker
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot_signaux_crypto.py

