services:
  - type: worker
    name: botcrypto-worker
    env: python
    region: frankfurt
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot_signaux_crypto.py
    autoDeploy: true
    restartPolicy: always
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
